title: Shoeshine.se - guider i skovård
email: ''
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://shoeshine.ehrenb.org"
github_username: GuTsaV
sass:
    sass_dir: _sass
    style: compressed
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - firebase.json
  - database.rules.json
  - README.md
  - favicon.psd
  - wip/
